INSERT INTO users VALUES(1,'zfathi','sha512$f1ce17ffd7c148718e58cec83f73eb33$c7e4a977c8e2d71a4a61e0441b838ece36ac57510cdef9a352949e51cb35a7186307b73d1e43f2b86f00f7d7470d1c3d39796fc41661cb2af0b1917979d9b2bb',24,69,165,'ma',1,'male');
INSERT INTO exercises VALUES(1,'chest','chest','Bar Dip','strength','bodyweight',0,4,4);
INSERT INTO exercises VALUES(2,'chest','chest','Bench Press','strength','barbell',0,5,5);
INSERT INTO exercises VALUES(3,'chest','chest','Cable Chest Press','strength','machine',2,3,3);
INSERT INTO exercises VALUES(4,'chest','chest','Close-Grip Bench Press','strength','barbell',0,3,3);
INSERT INTO exercises VALUES(5,'chest','chest','Close-Grip Feet-Up Bench Press','strength','barbell',2,2,2);
INSERT INTO exercises VALUES(6,'chest','lower-chest','Decline Bench Press','strength','barbell',0,3,3);
INSERT INTO exercises VALUES(7,'chest','chest','Dumbbell Chest Fly','strength','dumbbell',0,4,4);
INSERT INTO exercises VALUES(8,'chest','chest','Dumbbell Chest Press','strength','dumbbell',0,4,4);
INSERT INTO exercises VALUES(9,'chest','lower-chest','Dumbbell Decline Chest Press','strength','dumbbell',0,3,3);
INSERT INTO exercises VALUES(10,'chest','chest','Dumbbell Floor Press','strength','dumbbell',2,2,2);
INSERT INTO exercises VALUES(11,'back','lats','Dumbbell Pullover','strength','dumbbell',0,3,3);
INSERT INTO exercises VALUES(12,'chest','chest','Feet-Up Bench Press','strength','barbell',1,2,2);
INSERT INTO exercises VALUES(13,'chest','chest','Floor Press','strength','barbell',1,2,2);
INSERT INTO exercises VALUES(14,'chest','upper-chest','Incline Bench Press','strength','barbell',0,4,4);
INSERT INTO exercises VALUES(15,'chest','upper-chest','Incline Dumbbell Press','strength','dumbbell',0,5,5);
INSERT INTO exercises VALUES(16,'chest','upper-chest','Incline Push-Up','strength','bodyweight',0,3,3);
INSERT INTO exercises VALUES(17,'chest','upper-chest','Kneeling Incline Push-Up','strength','bodyweight',0,2,2);
INSERT INTO exercises VALUES(18,'chest','chest','Kneeling Push-Up','strength','bodyweight',0,2,2);
INSERT INTO exercises VALUES(19,'chest','chest','Machine Chest Fly','strength','machine',0,3,3);
INSERT INTO exercises VALUES(20,'chest','chest','Machine Chest Press','strength','machine',0,3,3);
INSERT INTO exercises VALUES(21,'chest','chest','Pec Deck','strength','machine',0,3,3);
INSERT INTO exercises VALUES(22,'chest','chest','Push-Up','strength','bodyweight',1,5,5);
INSERT INTO exercises VALUES(23,'chest','chest','Push-Up Against Wall','strength','bodyweight',0,1,1);
INSERT INTO exercises VALUES(24,'chest','chest','Push-Ups With Feet in Rings','strength','bodyweight',2,2,2);
INSERT INTO exercises VALUES(25,'chest','chest','Resistance Band Chest Fly','strength','band',1,2,2);
INSERT INTO exercises VALUES(26,'chest','chest','Standing Cable Chest Fly','strength','machine',0,3,3);
INSERT INTO exercises VALUES(27,'chest','chest','Standing Resistance Band Chest Fly','strength','band',0,2,2);
INSERT INTO exercises VALUES(28,'shoulders','anterior','Barbell Front Raise','strength','barbell',1,3,3);
INSERT INTO exercises VALUES(29,'shoulders','rear','Barbell Rear Delt Row','strength','barbell',1,3,3);
INSERT INTO exercises VALUES(30,'shoulders','lateral','Barbell Upright Row','strength','barbell',1,3,3);
INSERT INTO exercises VALUES(31,'shoulders','shoulder','Behind the Neck Press','strength','barbell',2,1,1);
INSERT INTO exercises VALUES(32,'shoulders','lateral','Cable Lateral Raise','strength','machine',0,3,3);
INSERT INTO exercises VALUES(33,'shoulders','rear','Cable Rear Delt Row','strength','machine',0,3,3);
INSERT INTO exercises VALUES(34,'shoulders','anterior','Dumbbell Front Raise','strength','dumbbell',0,3,3);
INSERT INTO exercises VALUES(35,'shoulders','lateral','Dumbbell Lateral Raise','strength','dumbbell',0,4,4);
INSERT INTO exercises VALUES(36,'shoulders','rear','Dumbbell Rear Delt Row','strength','dumbbell',0,3,3);
INSERT INTO exercises VALUES(37,'shoulders','shoulder','Dumbbell Shoulder Press','strength','dumbbell',0,4,4);
INSERT INTO exercises VALUES(38,'shoulders','rear','Face Pull','strength','machine',1,4,4);
INSERT INTO exercises VALUES(39,'shoulders','anterior','Front Hold','strength','bodyweight',1,1,1);
INSERT INTO exercises VALUES(40,'shoulders','lateral','Machine Lateral Raise','strength','machine',0,3,3);
INSERT INTO exercises VALUES(41,'shoulders','shoulder','Machine Shoulder Press','strength','machine',0,3,3);
INSERT INTO exercises VALUES(42,'shoulders','lateral','Monkey Row','strength','dumbbell',1,3,3);
INSERT INTO exercises VALUES(43,'shoulders','shoulder','Overhead Press','strength','barbell',0,5,5);
INSERT INTO exercises VALUES(44,'shoulders','anterior','Plate Front Raise','strength','plate',1,2,2);
INSERT INTO exercises VALUES(45,'shoulders','shoulder','Push Press','strength','barbell',1,4,4);
INSERT INTO exercises VALUES(46,'shoulders','rear','Reverse Cable Flyes','strength','machine',1,3,3);
INSERT INTO exercises VALUES(47,'shoulders','rear','Reverse Dumbbell Flyes','strength','dumbbell',0,3,3);
INSERT INTO exercises VALUES(48,'shoulders','rear','Reverse Machine Fly','strength','machine',0,3,3);
INSERT INTO exercises VALUES(49,'shoulders','shoulder','Seated Dumbbell Shoulder Press','strength','dumbbell',0,4,4);
INSERT INTO exercises VALUES(50,'shoulders','shoulder','Seated Barbell Overhead Press','strength','barbell',0,4,4);
INSERT INTO exercises VALUES(51,'shoulders','shoulder','Seated Smith Machine Shoulder Press','strength','machine',1,2,2);
INSERT INTO exercises VALUES(52,'shoulders','shoulder','Snatch Grip Behind the Neck Press','strength','barbell',2,1,1);
INSERT INTO exercises VALUES(53,'biceps','biceps','Barbell Curl','strength','barbell',0,4,4);
INSERT INTO exercises VALUES(54,'biceps','biceps','Barbell Preacher Curl','strength','barbell',1,3,3);
INSERT INTO exercises VALUES(55,'biceps','biceps','Bodyweight Curl','strength','bodyweight',1,2,2);
INSERT INTO exercises VALUES(56,'biceps','biceps','Cable Curl With Bar','strength','machine',0,4,4);
INSERT INTO exercises VALUES(57,'biceps','biceps','Cable Curl With Rope','strength','machine',0,3,3);
INSERT INTO exercises VALUES(58,'biceps','biceps','Concentration Curl','strength','dumbbell',0,4,4);
INSERT INTO exercises VALUES(59,'biceps','biceps','Dumbbell Curl','strength','dumbbell',0,5,5);
INSERT INTO exercises VALUES(60,'biceps','biceps','Dumbbell Preacher Curl','strength','dumbbell',1,3,3);
INSERT INTO exercises VALUES(61,'biceps','biceps','Hammer Curl','strength','dumbbell',0,4,4);
INSERT INTO exercises VALUES(62,'biceps','biceps','Incline Dumbbell Curl','strength','dumbbell',1,3,3);
INSERT INTO exercises VALUES(63,'biceps','biceps','Machine Bicep Curl','strength','machine',0,3,3);
INSERT INTO exercises VALUES(64,'biceps','biceps','Spider Curl','strength','barbell',1,3,3);
INSERT INTO exercises VALUES(65,'triceps','triceps','Barbell Standing Triceps Extension','strength','barbell',1,3,3);
INSERT INTO exercises VALUES(66,'triceps','triceps','Barbell Lying Triceps Extension','strength','barbell',1,3,3);
INSERT INTO exercises VALUES(67,'triceps','triceps','Bench Dip','strength','bodyweight',0,4,4);
INSERT INTO exercises VALUES(68,'triceps','triceps','Close-Grip Push-Up','strength','bodyweight',0,4,4);
INSERT INTO exercises VALUES(69,'triceps','triceps','Dumbbell Lying Triceps Extension','strength','dumbbell',0,5,5);
INSERT INTO exercises VALUES(70,'triceps','triceps','Dumbbell Standing Triceps Extension','strength','dumbbell',0,3,3);
INSERT INTO exercises VALUES(71,'triceps','triceps','Overhead Cable Triceps Extension','strength','machine',1,4,4);
INSERT INTO exercises VALUES(72,'triceps','triceps','Tricep Bodyweight Extension','strength','bodyweight',1,2,2);
INSERT INTO exercises VALUES(73,'triceps','triceps','Tricep Pushdown With Bar','strength','machine',0,4,4);
INSERT INTO exercises VALUES(74,'triceps','triceps','Tricep Pushdown With Rope','strength','machine',0,5,5);
INSERT INTO exercises VALUES(75,'legs','quads','Air Squat','strength','bodyweight',0,2,2);
INSERT INTO exercises VALUES(76,'legs','quads','Barbell Hack Squat','strength','barbell',1,4,4);
INSERT INTO exercises VALUES(77,'legs','legs','Barbell Lunge','strength','barbell',1,4,4);
INSERT INTO exercises VALUES(78,'legs','legs','Barbell Walking Lunge','strength','barbell',1,4,4);
INSERT INTO exercises VALUES(79,'legs','quads','Belt Squat','strength','machine',1,3,3);
INSERT INTO exercises VALUES(80,'legs','legs','Body Weight Lunge','strength','bodyweight',0,4,4);
INSERT INTO exercises VALUES(81,'legs','legs','Box Squat','strength','barbell',1,2,2);
INSERT INTO exercises VALUES(82,'legs','legs','Bulgarian Split Squat','strength','bodyweight',1,4,4);
INSERT INTO exercises VALUES(83,'legs','quads','Chair Squat','strength','bodyweight',0,1,1);
INSERT INTO exercises VALUES(84,'legs','legs','Dumbbell Lunge','strength','dumbbell',0,4,4);
INSERT INTO exercises VALUES(85,'legs','legs','Dumbbell Squat','strength','dumbbell',0,2,2);
INSERT INTO exercises VALUES(86,'legs','quads','Front Squat','strength','barbell',1,4,4);
INSERT INTO exercises VALUES(87,'legs','quads','Goblet Squat','strength','dumbbell',0,3,3);
INSERT INTO exercises VALUES(88,'legs','quads','Hack Squat Machine','strength','machine',0,4,4);
INSERT INTO exercises VALUES(89,'legs','quads','Half Air Squat','strength','bodyweight',0,1,1);
INSERT INTO exercises VALUES(90,'legs','adductors','Hip Adduction Machine','strength','machine',0,4,4);
INSERT INTO exercises VALUES(91,'legs','quads','Landmine Hack Squat','strength','barbell',1,2,2);
INSERT INTO exercises VALUES(92,'legs','legs','Landmine Squat','strength','barbell',1,2,2);
INSERT INTO exercises VALUES(93,'legs','quads','Leg Extension','strength','machine',0,5,5);
INSERT INTO exercises VALUES(94,'legs','legs','Leg Press','strength','machine',1,4,4);
INSERT INTO exercises VALUES(95,'legs','hamstrings','Lying Leg Curl','strength','machine',0,4,4);
INSERT INTO exercises VALUES(96,'legs','legs','Pause Squat','strength','barbell',1,2,2);
INSERT INTO exercises VALUES(97,'legs','hamstrings','Romanian Deadlift','strength','barbell',1,5,5);
INSERT INTO exercises VALUES(98,'legs','quads','Safety Bar Squat','strength','safety bar',1,2,2);
INSERT INTO exercises VALUES(99,'legs','hamstrings','Seated Leg Curl','strength','machine',0,4,4);
INSERT INTO exercises VALUES(100,'legs','quads','Shallow Body Weight Lunge','strength','bodyweight',0,3,3);
INSERT INTO exercises VALUES(101,'legs','quads','Side Lunges (Bodyweight)','strength','bodyweight',0,2,2);
INSERT INTO exercises VALUES(102,'legs','legs','Smith Machine Squat','strength','machine',0,3,3);
INSERT INTO exercises VALUES(103,'legs','legs','Squat','strength','barbell',0,5,5);
INSERT INTO exercises VALUES(104,'legs','legs','Dumbbell Step Up','strength','dumbbell',0,4,4);
INSERT INTO exercises VALUES(105,'back','lower-back','Back Extension','strength','bodyweight',0,2,2);
INSERT INTO exercises VALUES(106,'back','mid-back','Barbell Row','strength','barbell',0,5,5);
INSERT INTO exercises VALUES(107,'back','upper-back','Barbell Shrug','strength','barbell',0,3,3);
INSERT INTO exercises VALUES(108,'legs','legs','Block Snatch','olympic','barbell',2,4,4);
INSERT INTO exercises VALUES(109,'back','mid-back','Cable Close Grip Seated Row','strength','machine',0,4,4);
INSERT INTO exercises VALUES(110,'back','upper-back','Cable Wide Grip Seated Row','strength','machine',0,4,4);
INSERT INTO exercises VALUES(111,'back','lats','Chin-Up','strength','bodyweight',1,5,5);
INSERT INTO exercises VALUES(112,'legs','legs','Clean','olympic','barbell',2,5,5);
INSERT INTO exercises VALUES(113,'legs','legs','Clean and Jerk','olympic','barbell',2,5,5);
INSERT INTO exercises VALUES(114,'legs','legs','Deadlift','strength','barbell',0,5,5);
INSERT INTO exercises VALUES(115,'legs','lower-back','Deficit Deadlift','strength','barbell',1,4,4);
INSERT INTO exercises VALUES(116,'legs','legs','Dumbbell Deadlift','strength','dumbbell',0,3,3);
INSERT INTO exercises VALUES(117,'back','mid-back','Dumbbell Row','strength','dumbbell',0,5,5);
INSERT INTO exercises VALUES(118,'back','upper-back','Dumbbell Shrug','strength','dumbbell',0,4,4);
INSERT INTO exercises VALUES(119,'back','lower-back','Floor Back Extension','strength','bodyweight',0,1,1);
INSERT INTO exercises VALUES(120,'legs','glutes','Good Morning','strength','barbell',1,3,3);
INSERT INTO exercises VALUES(121,'legs','legs','Hang Clean','olympic','barbell',2,4,4);
INSERT INTO exercises VALUES(122,'legs','legs','Hang Power Clean','olympic','barbell',2,3,3);
INSERT INTO exercises VALUES(123,'legs','legs','Hang Power Snatch','olympic','barbell',2,3,3);
INSERT INTO exercises VALUES(124,'legs','legs','Hang Snatch','olympic','barbell',2,4,4);
INSERT INTO exercises VALUES(125,'back','mid-back','Inverted Row','strength','bodyweight',0,3,3);
INSERT INTO exercises VALUES(126,'back','mid-back','Inverted Row with Underhand Grip','strength','bodyweight',0,3,3);
INSERT INTO exercises VALUES(127,'back','lower-back','Jefferson Curl','strength','barbell',1,2,2);
INSERT INTO exercises VALUES(128,'legs','glutes','Kettlebell Swing','strength','kettlebell',1,4,4);
INSERT INTO exercises VALUES(129,'back','lats','Lat Pulldown With Pronated Grip','strength','machine',0,4,4);
INSERT INTO exercises VALUES(130,'back','lats','Lat Pulldown With Supinated Grip','strength','machine',0,4,4);
INSERT INTO exercises VALUES(131,'back','mid-back','One-Handed Cable Row','strength','cable',0,3,3);
INSERT INTO exercises VALUES(132,'back','lats','One-Handed Lat Pulldown','strength','cable',0,3,3);
INSERT INTO exercises VALUES(133,'legs','legs','Pause Deadlift','strength','barbell',1,4,4);
INSERT INTO exercises VALUES(134,'back','mid-back','Pendlay Row','strength','barbell',1,3,3);
INSERT INTO exercises VALUES(135,'legs','legs','Power Clean','olympic','barbell',2,4,4);
INSERT INTO exercises VALUES(136,'legs','legs','Power Snatch','olympic','barbell',2,4,4);
INSERT INTO exercises VALUES(137,'back','upper-back','Pull-Up','strength','bodyweight',1,5,5);
INSERT INTO exercises VALUES(138,'back','lower-back','Rack Pull','strength','barbell',2,2,2);
INSERT INTO exercises VALUES(139,'back','mid-back','Seal Row','strength','bench',1,3,3);
INSERT INTO exercises VALUES(140,'back','mid-back','Seated Machine Row','strength','machine',0,5,5);
INSERT INTO exercises VALUES(141,'legs','legs','Snatch','olympic','barbell',2,5,5);
INSERT INTO exercises VALUES(142,'legs','legs','Snatch Grip Deadlift','strength','barbell',2,2,2);
INSERT INTO exercises VALUES(143,'legs','hamstrings','Stiff-Legged Deadlift','strength','barbell',1,4,4);
INSERT INTO exercises VALUES(144,'back','lats','Straight Arm Lat Pulldown','strength','cable',0,3,3);
INSERT INTO exercises VALUES(145,'legs','legs','Sumo Deadlift','strength','barbell',1,4,4);
INSERT INTO exercises VALUES(146,'back','mid-back','T-Bar Row','strength','t-bar',1,4,4);
INSERT INTO exercises VALUES(147,'legs','legs','Trap Bar Deadlift With High Handles','strength','trap bar',0,4,4);
INSERT INTO exercises VALUES(148,'legs','legs','Trap Bar Deadlift With Low Handles','strength','trap bar',0,4,4);
INSERT INTO exercises VALUES(149,'legs','glutes','Cable Pull Through','strength','machine',1,3,3);
INSERT INTO exercises VALUES(150,'legs','glutes','Clamshells','warm-up','bodyweight',0,3,3);
INSERT INTO exercises VALUES(151,'legs','hamstrings','Dumbbell Romanian Deadlift','strength','dumbbell',0,4,4);
INSERT INTO exercises VALUES(152,'legs','glutes','Dumbbell Frog Pumps','strength','dumbbell',0,3,3);
INSERT INTO exercises VALUES(153,'legs','glutes','Fire Hydrants','warm-up','bodyweight',0,4,4);
INSERT INTO exercises VALUES(154,'legs','glutes','Frog Pumps','warm-up','bodyweight',0,3,3);
INSERT INTO exercises VALUES(155,'legs','glutes','Glute Bridge','strength','bodyweight',0,5,5);
INSERT INTO exercises VALUES(156,'legs','abductors','Hip Abduction Machine','strength','machine',0,4,4);
INSERT INTO exercises VALUES(157,'legs','glutes','Hip Thrust','strength','barbell',0,5,5);
INSERT INTO exercises VALUES(158,'legs','glutes','Hip Thrust Machine','strength','machine',0,4,4);
INSERT INTO exercises VALUES(159,'legs','glutes','Machine Glute Kickbacks','strength','machine',0,3,3);
INSERT INTO exercises VALUES(160,'legs','glutes','One-Legged Glute Bridge','strength','bodyweight',1,4,4);
INSERT INTO exercises VALUES(161,'legs','glutes','One-Legged Hip Thrust','strength','bodyweight',1,4,4);
INSERT INTO exercises VALUES(162,'legs','hamstrings','Romanian Deadlift','strength','barbell',0,5,5);
INSERT INTO exercises VALUES(163,'legs','hamstrings','Single Leg Romanian Deadlift','strength','dumbbell',1,4,4);
INSERT INTO exercises VALUES(164,'legs','glutes','Standing Glute Kickback in Machine','strength','machine',0,3,3);
INSERT INTO exercises VALUES(165,'abs','abs','Cable Crunch','strength','cable',1,3,3);
INSERT INTO exercises VALUES(166,'abs','abs','Crunch','strength','bodyweight',0,3,3);
INSERT INTO exercises VALUES(167,'abs','abs','Dead Bug','strength','bodyweight',0,4,4);
INSERT INTO exercises VALUES(168,'abs','abs','Hanging Leg Raise','strength','bodyweight',1,5,5);
INSERT INTO exercises VALUES(169,'abs','abs','Hanging Knee Raise','strength','bodyweight',0,4,4);
INSERT INTO exercises VALUES(170,'abs','abs','Hanging Sit-Up','strength','bodyweight',2,2,2);
INSERT INTO exercises VALUES(171,'abs','obliques','High to Low Wood Chop with Band','strength','band',0,3,3);
INSERT INTO exercises VALUES(172,'abs','obliques','Horizontal Wood Chop with Band','strength','band',0,4,4);
INSERT INTO exercises VALUES(173,'abs','abs','Kneeling Ab Wheel Roll-Out','strength','ab wheel',0,4,4);
INSERT INTO exercises VALUES(174,'abs','abs','Kneeling Plank','strength','bodyweight',0,4,4);
INSERT INTO exercises VALUES(175,'abs','obliques','Kneeling Side Plank','strength','bodyweight',0,4,4);
INSERT INTO exercises VALUES(176,'abs','abs','Lying Leg Raise','strength','bodyweight',0,5,5);
INSERT INTO exercises VALUES(177,'abs','obliques','Lying Windshield Wiper','strength','bodyweight',0,3,3);
INSERT INTO exercises VALUES(178,'abs','obliques','Lying Windshield Wiper with Bent Knees','strength','bodyweight',1,3,3);
INSERT INTO exercises VALUES(179,'abs','abs','Machine Crunch','strength','machine',0,2,2);
INSERT INTO exercises VALUES(180,'abs','abs','Mountain Climbers','strength','bodyweight',0,2,2);
INSERT INTO exercises VALUES(181,'abs','obliques','Oblique Crunch','strength','bodyweight',0,3,3);
INSERT INTO exercises VALUES(182,'abs','obliques','Oblique Sit-Up','strength','bodyweight',0,3,3);
INSERT INTO exercises VALUES(183,'abs','abs','Plank','strength','bodyweight',0,5,5);
INSERT INTO exercises VALUES(184,'abs','obliques','Side Plank','strength','bodyweight',0,5,5);
INSERT INTO exercises VALUES(185,'abs','abs','Sit-Up','strength','bodyweight',0,2,2);
INSERT INTO exercises VALUES(186,'legs','calves','Eccentric Heel Drop','strength','bodyweight',0,2,2);
INSERT INTO exercises VALUES(187,'legs','calves','Heel Raise','strength','bodyweight',0,4,4);
INSERT INTO exercises VALUES(188,'legs','calves','Seated Calf Raise','strength','machine',0,4,4);
INSERT INTO exercises VALUES(189,'legs','calves','Standing Dumbbell Calf Raise','strength','dumbbell',1,5,5);
INSERT INTO exercises VALUES(190,'legs','calves','Standing Calf Raise','strength','bodyweight',0,5,5);
INSERT INTO exercises VALUES(191,'back','upper-back','Weighted Pull-Up','strength','bodyweight',2,5,5);
INSERT INTO exercises VALUES(192,'back','lats','Weighted Chin-Up','strength','bodyweight',2,5,5);
INSERT INTO exercises VALUES(193,'back','lats','Negative Chin-Up','strength','bodyweight',0,5,5);
INSERT INTO exercises VALUES(194,'back','upper-back','Negative Pull-Up','strength','bodyweight',0,5,5);