INSERT INTO users VALUES(1,'zfathi','sha512$f1ce17ffd7c148718e58cec83f73eb33$c7e4a977c8e2d71a4a61e0441b838ece36ac57510cdef9a352949e51cb35a7186307b73d1e43f2b86f00f7d7470d1c3d39796fc41661cb2af0b1917979d9b2bb',24,69,165,'ma',1,'male');
INSERT INTO exercises VALUES(1,'chest','chest','dip','compound','Bar Dip','strength','bodyweight',0,4);
INSERT INTO exercises VALUES(2,'chest','chest','press','compound','Bench Press','strength','barbell',0,5);
INSERT INTO exercises VALUES(3,'chest','chest','press','compound','Cable Chest Press','strength','machine',2,3);
INSERT INTO exercises VALUES(4,'chest','chest','press','compound','Close-Grip Bench Press','strength','barbell',0,3);
INSERT INTO exercises VALUES(5,'chest','chest','press','compound','Close-Grip Feet-Up Bench Press','strength','barbell',2,2);
INSERT INTO exercises VALUES(6,'chest','lower-chest','press','compound','Decline Bench Press','strength','barbell',0,3);
INSERT INTO exercises VALUES(7,'chest','chest','fly','isolation','Dumbbell Chest Fly','strength','dumbbell',0,4);
INSERT INTO exercises VALUES(8,'chest','chest','press','compound','Dumbbell Chest Press','strength','dumbbell',0,4);
INSERT INTO exercises VALUES(9,'chest','lower-chest','press','compound','Dumbbell Decline Chest Press','strength','dumbbell',0,3);
INSERT INTO exercises VALUES(10,'chest','chest','press','compound','Dumbbell Floor Press','strength','dumbbell',2,2);
INSERT INTO exercises VALUES(11,'back','lats','press','compound','Dumbbell Pullover','strength','dumbbell',0,3);
INSERT INTO exercises VALUES(12,'chest','chest','press','compound','Feet-Up Bench Press','strength','barbell',1,2);
INSERT INTO exercises VALUES(13,'chest','chest','press','compound','Floor Press','strength','barbell',1,2);
INSERT INTO exercises VALUES(14,'chest','upper-chest','press','compound','Incline Bench Press','strength','barbell',0,4);
INSERT INTO exercises VALUES(15,'chest','upper-chest','press','compound','Incline Dumbbell Press','strength','dumbbell',0,5);
INSERT INTO exercises VALUES(16,'chest','upper-chest','push-up','compound','Incline Push-Up','strength','bodyweight',0,3);
INSERT INTO exercises VALUES(17,'chest','upper-chest','push-up','compound','Kneeling Incline Push-Up','strength','bodyweight',0,2);
INSERT INTO exercises VALUES(18,'chest','chest','push-up','compound','Kneeling Push-Up','strength','bodyweight',0,2);
INSERT INTO exercises VALUES(19,'chest','chest','fly','isolation','Machine Chest Fly','strength','machine',0,3);
INSERT INTO exercises VALUES(20,'chest','chest','press','compound','Machine Chest Press','strength','machine',0,3);
INSERT INTO exercises VALUES(21,'chest','chest','fly','isolation','Pec Deck','strength','machine',0,3);
INSERT INTO exercises VALUES(22,'chest','chest','push-up','compound','Push-Up','strength','bodyweight',1,5);
INSERT INTO exercises VALUES(23,'chest','chest','push-up','compound','Push-Up Against Wall','strength','bodyweight',0,1);
INSERT INTO exercises VALUES(24,'chest','chest','push-up','compound','Push-Ups With Feet in Rings','strength','bodyweight',2,2);
INSERT INTO exercises VALUES(25,'chest','chest','fly','isolation','Resistance Band Chest Fly','strength','band',1,2);
INSERT INTO exercises VALUES(26,'chest','chest','fly','isolation','Standing Cable Chest Fly','strength','machine',0,3);
INSERT INTO exercises VALUES(27,'chest','chest','fly','isolation','Standing Resistance Band Chest Fly','strength','band',0,2);
INSERT INTO exercises VALUES(28,'shoulders','anterior','raise','isolation','Barbell Front Raise','strength','barbell',1,3);
INSERT INTO exercises VALUES(29,'shoulders','rear','row','isolation','Barbell Rear Delt Row','strength','barbell',1,3);
INSERT INTO exercises VALUES(30,'shoulders','lateral','row','compound','Barbell Upright Row','strength','barbell',1,3);
INSERT INTO exercises VALUES(31,'shoulders','shoulder','vertical press','compound','Behind the Neck Press','strength','barbell',2,1);
INSERT INTO exercises VALUES(32,'shoulders','lateral','raise','isolation','Cable Lateral Raise','strength','machine',0,3);
INSERT INTO exercises VALUES(33,'shoulders','rear','row','isolation','Cable Rear Delt Row','strength','machine',0,3);
INSERT INTO exercises VALUES(34,'shoulders','anterior','raise','isolation','Dumbbell Front Raise','strength','dumbbell',0,3);
INSERT INTO exercises VALUES(35,'shoulders','lateral','raise','isolation','Dumbbell Lateral Raise','strength','dumbbell',0,4);
INSERT INTO exercises VALUES(36,'shoulders','rear','row','isolation','Dumbbell Rear Delt Row','strength','dumbbell',0,3);
INSERT INTO exercises VALUES(37,'shoulders','shoulder','vertical press','compound','Dumbbell Shoulder Press','strength','dumbbell',0,4);
INSERT INTO exercises VALUES(38,'shoulders','rear','pull','compound','Face Pull','strength','machine',1,4);
INSERT INTO exercises VALUES(39,'shoulders','anterior','raise','isolation','Front Hold','strength','bodyweight',1,1);
INSERT INTO exercises VALUES(40,'shoulders','lateral','raise','isolation','Machine Lateral Raise','strength','machine',0,3);
INSERT INTO exercises VALUES(41,'shoulders','shoulder','vertical press','compound','Machine Shoulder Press','strength','machine',0,3);
INSERT INTO exercises VALUES(42,'shoulders','lateral','row','compound','Monkey Row','strength','dumbbell',1,3);
INSERT INTO exercises VALUES(43,'shoulders','shoulder','vertical press','compound','Overhead Press','strength','barbell',0,5);
INSERT INTO exercises VALUES(44,'shoulders','anterior','raise','isolation','Plate Front Raise','strength','plate',1,2);
INSERT INTO exercises VALUES(45,'shoulders','shoulder','vertical press','compound','Push Press','strength','barbell',1,4);
INSERT INTO exercises VALUES(46,'shoulders','rear','fly','isolation','Reverse Cable Flyes','strength','machine',1,3);
INSERT INTO exercises VALUES(47,'shoulders','rear','fly','isolation','Reverse Dumbbell Flyes','strength','dumbbell',0,3);
INSERT INTO exercises VALUES(48,'shoulders','rear','fly','isolation','Reverse Machine Fly','strength','machine',0,3);
INSERT INTO exercises VALUES(49,'shoulders','shoulder','vertical press','compound','Seated Dumbbell Shoulder Press','strength','dumbbell',0,4);
INSERT INTO exercises VALUES(50,'shoulders','shoulder','vertical press','compound','Seated Barbell Overhead Press','strength','barbell',0,4);
INSERT INTO exercises VALUES(51,'shoulders','shoulder','vertical press','compound','Seated Smith Machine Shoulder Press','strength','machine',1,2);
INSERT INTO exercises VALUES(52,'shoulders','shoulder','vertical press','compound','Snatch Grip Behind the Neck Press','strength','barbell',2,1);
INSERT INTO exercises VALUES(53,'biceps','biceps','curl','isolation','Barbell Curl','strength','barbell',0,4);
INSERT INTO exercises VALUES(54,'biceps','biceps','curl','isolation','Barbell Preacher Curl','strength','barbell',1,3);
INSERT INTO exercises VALUES(55,'biceps','biceps','curl','compound','Bodyweight Curl','strength','bodyweight',1,2);
INSERT INTO exercises VALUES(56,'biceps','biceps','curl','isolation','Cable Curl With Bar','strength','machine',0,4);
INSERT INTO exercises VALUES(57,'biceps','biceps','curl','isolation','Cable Curl With Rope','strength','machine',0,3);
INSERT INTO exercises VALUES(58,'biceps','biceps','curl','isolation','Concentration Curl','strength','dumbbell',0,4);
INSERT INTO exercises VALUES(59,'biceps','biceps','curl','isolation','Dumbbell Curl','strength','dumbbell',0,5);
INSERT INTO exercises VALUES(60,'biceps','biceps','curl','isolation','Dumbbell Preacher Curl','strength','dumbbell',1,3);
INSERT INTO exercises VALUES(61,'biceps','biceps','curl','isolation','Hammer Curl','strength','dumbbell',0,4);
INSERT INTO exercises VALUES(62,'biceps','biceps','curl','isolation','Incline Dumbbell Curl','strength','dumbbell',1,3);
INSERT INTO exercises VALUES(63,'biceps','biceps','curl','isolation','Machine Bicep Curl','strength','machine',0,3);
INSERT INTO exercises VALUES(64,'biceps','biceps','curl','isolation','Spider Curl','strength','barbell',1,3);
INSERT INTO exercises VALUES(65,'triceps','triceps','extension','isolation','Barbell Standing Triceps Extension','strength','barbell',1,3);
INSERT INTO exercises VALUES(66,'triceps','triceps','extension','isolation','Barbell Lying Triceps Extension','strength','barbell',1,3);
INSERT INTO exercises VALUES(67,'triceps','triceps','dip','compound','Bench Dip','strength','bodyweight',0,4);
INSERT INTO exercises VALUES(68,'triceps','triceps','push-up','compound','Close-Grip Push-Up','strength','bodyweight',0,4);
INSERT INTO exercises VALUES(69,'triceps','triceps','extension','isolation','Dumbbell Lying Triceps Extension','strength','dumbbell',0,5);
INSERT INTO exercises VALUES(70,'triceps','triceps','extension','isolation','Dumbbell Standing Triceps Extension','strength','dumbbell',0,3);
INSERT INTO exercises VALUES(71,'triceps','triceps','extension','isolation','Overhead Cable Triceps Extension','strength','machine',1,4);
INSERT INTO exercises VALUES(72,'triceps','triceps','extension','isolation','Tricep Bodyweight Extension','strength','bodyweight',1,2);
INSERT INTO exercises VALUES(73,'triceps','triceps','extension','isolation','Tricep Pushdown With Bar','strength','machine',0,4);
INSERT INTO exercises VALUES(74,'triceps','triceps','extension','isolation','Tricep Pushdown With Rope','strength','machine',0,5);
INSERT INTO exercises VALUES(75,'legs','quads','squat','compound','Air Squat','strength','bodyweight',0,2);
INSERT INTO exercises VALUES(76,'legs','quads','squat','compound','Barbell Hack Squat','strength','barbell',1,4);
INSERT INTO exercises VALUES(77,'legs','legs','lunge','compound','Barbell Lunge','strength','barbell',1,4);
INSERT INTO exercises VALUES(78,'legs','legs','lunge','compound','Barbell Walking Lunge','strength','barbell',1,4);
INSERT INTO exercises VALUES(79,'legs','quads','squat','compound','Belt Squat','strength','machine',1,3);
INSERT INTO exercises VALUES(80,'legs','legs','lunge','compound','Body Weight Lunge','strength','bodyweight',0,4);
INSERT INTO exercises VALUES(81,'legs','legs','squat','compound','Box Squat','strength','barbell',1,2);
INSERT INTO exercises VALUES(82,'legs','legs','squat','compound','Bulgarian Split Squat','strength','bodyweight',1,4);
INSERT INTO exercises VALUES(83,'legs','quads','squat','compound','Chair Squat','strength','bodyweight',0,1);
INSERT INTO exercises VALUES(84,'legs','legs','lunge','compound','Dumbbell Lunge','strength','dumbbell',0,4);
INSERT INTO exercises VALUES(85,'legs','legs','squat','compound','Dumbbell Squat','strength','dumbbell',0,2);
INSERT INTO exercises VALUES(86,'legs','quads','squat','compound','Front Squat','strength','barbell',1,4);
INSERT INTO exercises VALUES(87,'legs','quads','squat','compound','Goblet Squat','strength','dumbbell',0,3);
INSERT INTO exercises VALUES(88,'legs','quads','squat','compound','Hack Squat Machine','strength','machine',0,4);
INSERT INTO exercises VALUES(89,'legs','quads','squat','compound','Half Air Squat','strength','bodyweight',0,1);
INSERT INTO exercises VALUES(90,'legs','adductors','adduction','compound','Hip Adduction Machine','strength','machine',0,4);
INSERT INTO exercises VALUES(91,'legs','quads','squat','compound','Landmine Hack Squat','strength','barbell',1,2);
INSERT INTO exercises VALUES(92,'legs','legs','squat','compound','Landmine Squat','strength','barbell',1,2);
INSERT INTO exercises VALUES(93,'legs','quads','extension','isolation','Leg Extension','strength','machine',0,5);
INSERT INTO exercises VALUES(94,'legs','legs','leg-press','isolation','Leg Press','strength','machine',1,4);
INSERT INTO exercises VALUES(95,'legs','hamstrings','leg-curl','isolation','Lying Leg Curl','strength','machine',0,4);
INSERT INTO exercises VALUES(96,'legs','legs','squat','compound','Pause Squat','strength','barbell',1,2);
INSERT INTO exercises VALUES(97,'legs','hamstrings','deadlift','compound','Romanian Deadlift','strength','barbell',1,5);
INSERT INTO exercises VALUES(98,'legs','quads','squat','compound','Safety Bar Squat','strength','safety bar',1,2);
INSERT INTO exercises VALUES(99,'legs','hamstrings','leg-curl','isolation','Seated Leg Curl','strength','machine',0,4);
INSERT INTO exercises VALUES(100,'legs','quads','lunge','compound','Shallow Body Weight Lunge','strength','bodyweight',0,3);
INSERT INTO exercises VALUES(101,'legs','quads','lunge','compound','Side Lunges (Bodyweight)','strength','bodyweight',0,2);
INSERT INTO exercises VALUES(102,'legs','legs','squat','compound','Smith Machine Squat','strength','machine',0,3);
INSERT INTO exercises VALUES(103,'legs','legs','squat','compound','Squat','strength','barbell',0,5);
INSERT INTO exercises VALUES(104,'legs','legs','step-up','compound','Dumbbell Step Up','strength','dumbbell',0,4);
INSERT INTO exercises VALUES(105,'back','lower-back','back-extension','compound','Back Extension','strength','bodyweight',0,2);
INSERT INTO exercises VALUES(106,'back','mid-back','row','compound','Barbell Row','strength','barbell',0,5);
INSERT INTO exercises VALUES(107,'back','upper-back','shrug','compound','Barbell Shrug','strength','barbell',0,3);
INSERT INTO exercises VALUES(108,'legs','legs','snatch','compound','Block Snatch','olympic','barbell',2,4);
INSERT INTO exercises VALUES(109,'back','mid-back','row','compound','Cable Close Grip Seated Row','strength','machine',0,4);
INSERT INTO exercises VALUES(110,'back','upper-back','row','compound','Cable Wide Grip Seated Row','strength','machine',0,4);
INSERT INTO exercises VALUES(111,'back','lats','pull-up','compound','Chin-Up','strength','bodyweight',1,5);
INSERT INTO exercises VALUES(112,'legs','legs','clean','compound','Clean','olympic','barbell',2,5);
INSERT INTO exercises VALUES(113,'legs','legs','clean','compound','Clean and Jerk','olympic','barbell',2,5);
INSERT INTO exercises VALUES(114,'legs','legs','deadlift','compound','Deadlift','strength','barbell',0,5);
INSERT INTO exercises VALUES(115,'legs','lower-back','deadlift','compound','Deficit Deadlift','strength','barbell',1,4);
INSERT INTO exercises VALUES(116,'legs','legs','deadlift','compound','Dumbbell Deadlift','strength','dumbbell',0,3);
INSERT INTO exercises VALUES(117,'back','mid-back','row','compound','Dumbbell Row','strength','dumbbell',0,5);
INSERT INTO exercises VALUES(118,'back','upper-back','shrug','compound','Dumbbell Shrug','strength','dumbbell',0,4);
INSERT INTO exercises VALUES(119,'back','lower-back','back-extension','isolation','Floor Back Extension','strength','bodyweight',0,1);
INSERT INTO exercises VALUES(120,'legs','glutes','back-extension','compound','Good Morning','strength','barbell',1,3);
INSERT INTO exercises VALUES(121,'legs','legs','clean','compound','Hang Clean','olympic','barbell',2,4);
INSERT INTO exercises VALUES(122,'legs','legs','clean','compound','Hang Power Clean','olympic','barbell',2,3);
INSERT INTO exercises VALUES(123,'legs','legs','snatch','compound','Hang Power Snatch','olympic','barbell',2,3);
INSERT INTO exercises VALUES(124,'legs','legs','snatch','compound','Hang Snatch','olympic','barbell',2,4);
INSERT INTO exercises VALUES(125,'back','mid-back','row','compound','Inverted Row','strength','bodyweight',0,3);
INSERT INTO exercises VALUES(126,'back','mid-back','row','compound','Inverted Row with Underhand Grip','strength','bodyweight',0,3);
INSERT INTO exercises VALUES(127,'back','lower-back','black-flexion','compound','Jefferson Curl','strength','barbell',1,2);
INSERT INTO exercises VALUES(128,'legs','glutes','hip-hinge','compound','Kettlebell Swing','strength','kettlebell',1,4);
INSERT INTO exercises VALUES(129,'back','lats','pull-up','compound','Lat Pulldown With Pronated Grip','strength','machine',0,4);
INSERT INTO exercises VALUES(130,'back','lats','pull-up','compound','Lat Pulldown With Supinated Grip','strength','machine',0,4);
INSERT INTO exercises VALUES(131,'back','mid-back','row','compound','One-Handed Cable Row','strength','cable',0,3);
INSERT INTO exercises VALUES(132,'back','lats','pull-up','compound','One-Handed Lat Pulldown','strength','cable',0,3);
INSERT INTO exercises VALUES(133,'legs','legs','deadlift','compound','Pause Deadlift','strength','barbell',1,4);
INSERT INTO exercises VALUES(134,'back','mid-back','row','compound','Pendlay Row','strength','barbell',1,3);
INSERT INTO exercises VALUES(135,'legs','legs','clean','compound','Power Clean','olympic','barbell',2,4);
INSERT INTO exercises VALUES(136,'legs','legs','snatch','compound','Power Snatch','olympic','barbell',2,4);
INSERT INTO exercises VALUES(137,'back','upper-back','pull-up','compound','Pull-Up','strength','bodyweight',1,5);
INSERT INTO exercises VALUES(138,'back','lower-back','back-extension','compound','Rack Pull','strength','barbell',2,2);
INSERT INTO exercises VALUES(139,'back','mid-back','row','compound','Seal Row','strength','bench',1,3);
INSERT INTO exercises VALUES(140,'back','mid-back','row','compound','Seated Machine Row','strength','machine',0,5);
INSERT INTO exercises VALUES(141,'legs','legs','snatch','compound','Snatch','olympic','barbell',2,5);
INSERT INTO exercises VALUES(142,'legs','legs','deadlift','compound','Snatch Grip Deadlift','strength','barbell',2,2);
INSERT INTO exercises VALUES(143,'legs','hamstrings','deadlift','compound','Stiff-Legged Deadlift','strength','barbell',1,4);
INSERT INTO exercises VALUES(144,'back','lats','pull-up','compound','Straight Arm Lat Pulldown','strength','cable',0,3);
INSERT INTO exercises VALUES(145,'legs','legs','deadlift','compound','Sumo Deadlift','strength','barbell',1,4);
INSERT INTO exercises VALUES(146,'back','mid-back','row','compound','T-Bar Row','strength','t-bar',1,4);
INSERT INTO exercises VALUES(147,'legs','legs','deadlift','compound','Trap Bar Deadlift With High Handles','strength','trap bar',0,4);
INSERT INTO exercises VALUES(148,'legs','legs','deadlift','compound','Trap Bar Deadlift With Low Handles','strength','trap bar',0,4);
INSERT INTO exercises VALUES(149,'legs','glutes','hip-hinge','isolation','Cable Pull Through','strength','machine',1,3);
INSERT INTO exercises VALUES(150,'legs','glutes','abduction','isolation','Clamshells','warm-up','bodyweight',0,3);
INSERT INTO exercises VALUES(151,'legs','hamstrings','deadlift','compound','Dumbbell Romanian Deadlift','strength','dumbbell',0,4);
INSERT INTO exercises VALUES(152,'legs','glutes','frog-pumps','isolation','Dumbbell Frog Pumps','strength','dumbbell',0,3);
INSERT INTO exercises VALUES(153,'legs','glutes','fire-hydrants','compound','Fire Hydrants','warm-up','bodyweight',0,4);
INSERT INTO exercises VALUES(154,'legs','glutes','frog-pumps','isolation','Frog Pumps','warm-up','bodyweight',0,3);
INSERT INTO exercises VALUES(155,'legs','glutes','thrust','compound','Glute Bridge','strength','bodyweight',0,5);
INSERT INTO exercises VALUES(156,'legs','abductors','abduction','isolation','Hip Abduction Machine','strength','machine',0,4);
INSERT INTO exercises VALUES(157,'legs','glutes','thrust','compound','Hip Thrust','strength','barbell',0,5);
INSERT INTO exercises VALUES(158,'legs','glutes','thrust','compound','Hip Thrust Machine','strength','machine',0,4);
INSERT INTO exercises VALUES(159,'legs','glutes','kickback','isolation','Machine Glute Kickbacks','strength','machine',0,3);
INSERT INTO exercises VALUES(160,'legs','glutes','thrust','compound','One-Legged Glute Bridge','strength','bodyweight',1,4);
INSERT INTO exercises VALUES(161,'legs','glutes','thrust','compound','One-Legged Hip Thrust','strength','bodyweight',1,4);
INSERT INTO exercises VALUES(162,'legs','hamstrings','deadlift','compound','Romanian Deadlift','strength','barbell',0,5);
INSERT INTO exercises VALUES(163,'legs','hamstrings','deadlift','compound','Single Leg Romanian Deadlift','strength','dumbbell',1,4);
INSERT INTO exercises VALUES(164,'legs','glutes','kickback','isolation','Standing Glute Kickback in Machine','strength','machine',0,3);
INSERT INTO exercises VALUES(165,'abs','abs','crunch','isolation','Cable Crunch','strength','cable',1,3);
INSERT INTO exercises VALUES(166,'abs','abs','crunch','isolation','Crunch','strength','bodyweight',0,3);
INSERT INTO exercises VALUES(167,'abs','abs','dead-bug','isolation','Dead Bug','strength','bodyweight',0,4);
INSERT INTO exercises VALUES(168,'abs','abs','leg-raise','isolation','Hanging Leg Raise','strength','bodyweight',1,5);
INSERT INTO exercises VALUES(169,'abs','abs','knee-raise','isolation','Hanging Knee Raise','strength','bodyweight',0,4);
INSERT INTO exercises VALUES(170,'abs','abs','sit-up','isolation','Hanging Sit-Up','strength','bodyweight',2,2);
INSERT INTO exercises VALUES(171,'abs','obliques','wood-chop','isolation','High to Low Wood Chop with Band','strength','band',0,3);
INSERT INTO exercises VALUES(172,'abs','obliques','wood-chop','isolation','Horizontal Wood Chop with Band','strength','band',0,4);
INSERT INTO exercises VALUES(173,'abs','abs','ab-wheel','isolation','Kneeling Ab Wheel Roll-Out','strength','ab wheel',0,4);
INSERT INTO exercises VALUES(174,'abs','abs','plank','isolation','Kneeling Plank','strength','bodyweight',0,4);
INSERT INTO exercises VALUES(175,'abs','obliques','plank','isolation','Kneeling Side Plank','strength','bodyweight',0,4);
INSERT INTO exercises VALUES(176,'abs','abs','leg-raise','isolation','Lying Leg Raise','strength','bodyweight',0,5);
INSERT INTO exercises VALUES(177,'abs','obliques','windshield-wiper','isolation','Lying Windshield Wiper','strength','bodyweight',0,3);
INSERT INTO exercises VALUES(178,'abs','obliques','windshield-wiper','isolation','Lying Windshield Wiper with Bent Knees','strength','bodyweight',1,3);
INSERT INTO exercises VALUES(179,'abs','abs','crunch','isolation','Machine Crunch','strength','machine',0,2);
INSERT INTO exercises VALUES(180,'abs','abs','mountain-climber','isolation','Mountain Climbers','strength','bodyweight',0,2);
INSERT INTO exercises VALUES(181,'abs','obliques','crunch','isolation','Oblique Crunch','strength','bodyweight',0,3);
INSERT INTO exercises VALUES(182,'abs','obliques','sit-up','isolation','Oblique Sit-Up','strength','bodyweight',0,3);
INSERT INTO exercises VALUES(183,'abs','abs','plank','isolation','Plank','strength','bodyweight',0,5);
INSERT INTO exercises VALUES(184,'abs','obliques','plank','isolation','Side Plank','strength','bodyweight',0,5);
INSERT INTO exercises VALUES(185,'abs','abs','sit-up','isolation','Sit-Up','strength','bodyweight',0,2);
INSERT INTO exercises VALUES(186,'legs','calves','heel-drop','isolation','Eccentric Heel Drop','strength','bodyweight',0,2);
INSERT INTO exercises VALUES(187,'legs','calves','heel-raise','isolation','Heel Raise','strength','bodyweight',0,4);
INSERT INTO exercises VALUES(188,'legs','calves','calf-raise','isolation','Seated Calf Raise','strength','machine',0,4);
INSERT INTO exercises VALUES(189,'legs','calves','calf-raise','isolation','Standing Dumbbell Calf Raise','strength','dumbbell',1,5);
INSERT INTO exercises VALUES(190,'legs','calves','calf-raise','isolation','Standing Calf Raise','strength','bodyweight',0,5);
INSERT INTO exercises VALUES(191,'back','upper-back','pull-up','compound','Weighted Pull-Up','strength','bodyweight',2,5);
INSERT INTO exercises VALUES(192,'back','lats','pull-up','compound','Weighted Chin-Up','strength','bodyweight',2,5);
INSERT INTO exercises VALUES(193,'back','lats','pull-up','compound','Negative Chin-Up','strength','bodyweight',0,5);
INSERT INTO exercises VALUES(194,'back','upper-back','pull-up','compound','Negative Pull-Up','strength','bodyweight',0,5);